# Extremely basic development setup to serve the current directory at http://localhost:9001
# Start nginx in this directory with `nginx -p . -c nginx.conf`
# Stop nginx with `nginx -p . -s stop`

pid       /tmp/nginx.pid;
events {}

http {
    access_log  off;
    error_log off;

    server {
        listen 9001;

        root .;
        location / {
          
        }
        location ~ \.css {
            add_header  Content-Type    text/css;
        }
        location ~ \.js {
            add_header  Content-Type    application/x-javascript;
        }
    }
}
